<a href="https://colab.research.google.com/github/arislaoliveira/Analise-de-dados/blob/main/aula_12_4_prof_ipynb_txt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Aula 12/04

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('Dados6.csv')

In [ ]:
df_limpo = df.dropna()

df_limpo

            nome  idade altura   peso  distancia  moradores  pets Unnamed: 7
21  Luiz Alencar     23   1.86  105.0       15.0        4.0   2.0

In [ ]:
media_peso = df['peso'].mean()

df['peso'] = df['peso'].fillna(media_peso)

In [ ]:
df = df.drop('Unnamed: 7', axis=1)
print(df)

                                       nome  idade altura        peso  \
0                            Vitor Ramirez      17   1.87   64.000000
1                 Rodrigo Caetano Mercante      19   1.87   78.000000
2                           guilherme prado     23   1.78   92.000000
3                    Wilma Augusto da Silva     19   1.68   69.000000
4                Sara Rodrigues dos Santos      24   1.71   83.000000
5                              Hiago Branco     30   1.82  150.000000
6                         Raphaela Cristine     21   1.77  130.000000
7          Gabriel Rodrigues de Moura Pinto     20   1.69   67.000000
8                  Beatriz Gomes de Almeida     21   1.73   78.000000
9                    Rafaella Souza Corrêa      18   1.55   59.000000
10         Antonio Augusto de Santa Rita Jr     22   1.78   78.000000
11          Vinícius Eduardo Romero Araújo      22   1.83   76.000000
12                   Felipe Gonzalez Santos     22   1.80   84.000000
13           Paulo Renan Mathias dos Santos     21   1.85   75.000000
14           Lucas Henrique da Silva Costa      21   1.78   97.000000
15                  Gabriela Cravo Miranda      24   1.65   67.000000
16                            luana almeida     18   1.75   58.000000
17                         Raissa de França     18   1.55   50.000000
18                          manuela vancini     21   1.62   67.000000
19                layanne stephany stopelli     18   1.67   61.000000
20                    Giovanni Bordin Oséas     19   1.74   74.000000
21                             Luiz Alencar     23   1.86  105.000000
22                             Milena Neves     20   1.60   46.000000
23                   Murillo Carvalho Amate     21   1.70   76.000000
24                       Catharine Peripato     21   1.66   78.000000
25               Bárbara Luiza Nunes Idalgo     18   1.68   56.000000
26                   Gildo Feliciano Vieira     26   1.80   80.000000
27             João Victor dos Santos Silva     19   1.77   90.000000
28          Carlos Eduardo Teixeira Aguilar     22   1.72   65.000000
29                             Laura Lilian     26   1.55   55.000000
30                        Eric Vasconcelos      34   1.75   90.000000
31      Victor Davi Fernandes Martins Costa     22   1.78   72.000000
32             João Vitor Fernandes Euzebio     21   1.75   83.000000
33                           Cássia Althman     19   1,55   40.000000
34                 Maria Eduarda Guimarães      24   1.60   69.000000
35               Wesley Silveira dos Santos     28   1.87   80.000000
36              Caroline Ribeiro dos Santos     22   1.57   63.000000
37         Weslley Moreira Lombas de Souza      26   1.70   74.000000
38                     Aline Alves de Souza     32   1.50   92.000000
39                  Gustavo Sampaio Moreira     20   1.83   69.000000
40  Pedro Henrique Alves Basilio Dos Santos     21   1.86   70.000000
41                        Guilherme Garrido     22   1.66   52.000000
42                           André De Maria     19   1.90   94.000000
43                               João Pedro     19   1.80   65.000000
44                Arisla Santos de Oliveira     23   1.58   60.000000
45             Guilherme De Souza Carvalho      19   1.75   66.000000
46                 Emilly da Silva Bezerra      23   1.70   56.000000
47                         Matheus Fuscaldi     20   1.70   78.000000
48                    Guilherme Ken Hanaoka     21   1.71   85.000000
49                    Melina Carvalho Cunha     19   1.62   66.000000
50                             Inara Galvao     24   1.64   66.000000
51             Henrique Da Silva Gonçalves      24   1.90  105.000000
52           Nathalia Cristina de Oliveira      22   1.60   60.000000
53                    Gabriel Guedes Coelho     27   1.78   86.000000
54         Ana Luiza Leite de Melo Geraldo      18   1.64   61.000000
55                     Aline Alves de Souza     32   1.50   92.000000
56                    Lucas Santos Carvalho     20    NaN   75.035714

    distancia  moradores  pets
0        15.0        5.0   2.0
1        20.0        1.0   0.0
2        26.1        2.0   1.0
3        25.1        3.0   1.0
4         9.8        4.0   2.0
5         9.0        1.0   0.0
6        18.0        2.0   0.0
7         3.0        2.0   0.0
8        28.0        2.0   1.0
9        17.0        2.0   0.0
10       28.0        4.0   4.0
11       16.8        2.0   0.0
12       15.0        3.0   0.0
13       78.0        3.0   1.0
14       14.0        4.0   1.0
15       21.0        4.0   3.0
16       21.4        3.0   1.0
17       21.4        4.0   1.0
18       16.0        2.0   0.0
19       28.0        3.0   1.0
20       11.0        4.0   0.0
21       15.0        4.0   2.0
22        NaN        4.0   1.0
23       24.0        4.0   0.0
24       26.0        3.0   1.0
25       29.0        4.0   2.0
26       25.4        3.0   0.0
27       30.0        5.0   4.0
28       12.0        2.0  10.0
29       10.0        1.0   0.0
30       11.0        4.0   0.0
31       12.0        4.0   0.0
32       16.0        6.0   1.0
33       20.0        3.0   3.0
34        NaN        NaN   1.0
35       31.0        1.0   0.0
36       22.0        2.0   2.0
37       14.0        5.0   2.0
38       18.0        3.0   NaN
39       29.0        3.0   1.0
40       51.6        3.0   2.0
41       22.0        3.0   1.0
42       12.0        4.0   1.0
43       15.0        3.0   0.0
44       17.1        4.0   4.0
45       41.5        4.0   2.0
46       24.0        3.0   1.0
47        5.5        3.0   0.0
48       10.0        3.0   1.0
49       23.0        2.0   0.0
50       21.0        5.0   1.0
51       24.0        2.0   0.0
52       20.0        1.0   0.0
53       10.0        2.0   1.0
54       23.0        3.0   9.0
55       18.0        3.0   2.0
56        NaN        NaN   NaN

In [ ]:
df_sem_duplicados = df.drop_duplicates()
display(df_sem_duplicados)

,nome,idade,altura,peso,distancia,moradores,pets
0,Vitor Ramirez,17,1.87,64.000000,15.0,5.0,2.0
1,Rodrigo Caetano Mercante,19,1.87,78.000000,20.0,1.0,0.0
2,guilherme prado,23,1.78,92.000000,26.1,2.0,1.0
3,Wilma Augusto da Silva,19,1.68,69.000000,25.1,3.0,1.0
4,Sara Rodrigues dos Santos,24,1.71,83.000000,9.8,4.0,2.0
5,Hiago Branco,30,1.82,150.000000,9.0,1.0,0.0
6,Raphaela Cristine,21,1.77,130.000000,18.0,2.0,0.0
7,Gabriel Rodrigues de Moura Pinto,20,1.69,67.000000,3.0,2.0,0.0
8,Beatriz Gomes de Almeida,21,1.73,78.000000,28.0,2.0,1.0
9,Rafaella Souza Corrêa,18,1.55,59.000000,17.0,2.0,0.0
10,Antonio Augusto de Santa Rita Jr,22,1.78,78.000000,28.0,4.0,4.0
11,Vinícius Eduardo Romero Araújo,22,1.83,76.000000,16.8,2.0,0.0
12,Felipe Gonzalez Santos,22,1.80,84.000000,15.0,3.0,0.0
13,Paulo Renan Mathias dos Santos,21,1.85,75.000000,78.0,3.0,1.0
14,Lucas Henrique da Silva Costa,21,1.78,97.000000,14.0,4.0,1.0
15,Gabriela Cravo Miranda,24,1.65,67.000000,21.0,4.0,3.0
16,luana almeida,18,1.75,58.000000,21.4,3.0,1.0
17,Raissa de França,18,1.55,50.000000,21.4,4.0,1.0
18,manuela vancini,21,1.62,67.000000,16.0,2.0,0.0
19,layanne stephany stopelli,18,1.67,61.000000,28.0,3.0,1.0
20,Giovanni Bordin Oséas,19,1.74,74.000000,11.0,4.0,0.0
21,Luiz Alencar,23,1.86,105.000000,15.0,4.0,2.0
22,Milena Neves,20,1.60,46.000000,NaN,4.0,1.0
23,Murillo Carvalho Amate,21,1.70,76.000000,24.0,4.0,0.0
24,Catharine Peripato,21,1.66,78.000000,26.0,3.0,1.0
25,Bárbara Luiza Nunes Idalgo,18,1.68,56.000000,29.0,4.0,2.0
26,Gildo Feliciano Vieira,26,1.80,80.000000,25.4,3.0,0.0
27,João Victor dos Santos Silva,19,1.77,90.000000,30.0,5.0,4.0
28,Carlos Eduardo Teixeira Aguilar,22,1.72,65.000000,12.0,2.0,10.0
29,Laura Lilian,26,1.55,55.000000,10.0,1.0,0.0
30,Eric Vasconcelos,34,1.75,90.000000,11.0,4.0,0.0
31,Victor Davi Fernandes Martins Costa,22,1.78,72.000000,12.0,4.0,0.0
32,João Vitor Fernandes Euzebio,21,1.75,83.000000,16.0,6.0,1.0
33,Cássia Althman,19,"1,55",40.000000,20.0,3.0,3.0
34,Maria Eduarda Guimarães,24,1.60,69.000000,NaN,NaN,1.0
35,Wesley Silveira dos Santos,28,1.87,80.000000,31.0,1.0,0.0
36,Caroline Ribeiro dos Santos,22,1.57,63.000000,22.0,2.0,2.0
37,Weslley Moreira Lombas de Souza,26,1.70,74.000000,14.0,5.0,2.0
38,Aline Alves de Souza,32,1.50,92.000000,18.0,3.0,NaN
39,Gustavo Sampaio Moreira,20,1.83,69.000000,29.0,3.0,1.0
40,Pedro Henrique Alves Basilio Dos Santos,21,1.86,70.000000,51.6,3.0,2.0
41,Guilherme Garrido,22,1.66,52.000000,22.0,3.0,1.0
42,André De Maria,19,1.90,94.000000,12.0,4.0,1.0
43,João Pedro,19,1.80,65.000000,15.0,3.0,0.0
44,Arisla Santos de Oliveira,23,1.58,60.000000,17.1,4.0,4.0
45,Guilherme De Souza Carvalho,19,1.75,66.000000,41.5,4.0,2.0
46,Emilly da Silva Bezerra,23,1.70,56.000000,24.0,3.0,1.0
47,Matheus Fuscaldi,20,1.70,78.000000,5.5,3.0,0.0
48,Guilherme Ken Hanaoka,21,1.71,85.000000,10.0,3.0,1.0
49,Melina Carvalho Cunha,19,1.62,66.000000,23.0,2.0,0.0
50,Inara Galvao,24,1.64,66.000000,21.0,5.0,1.0
51,Henrique Da Silva Gonçalves,24,1.90,105.000000,24.0,2.0,0.0
52,Nathalia Cristina de Oliveira,22,1.60,60.000000,20.0,1.0,0.0
53,Gabriel Guedes Coelho,27,1.78,86.000000,10.0,2.0,1.0
54,Ana Luiza Leite de Melo Geraldo,18,1.64,61.000000,23.0,3.0,9.0
55,Aline Alves de Souza,32,1.50,92.000000,18.0,3.0,2.0
56,Lucas Santos Carvalho,20,NaN,75.035714,NaN,NaN,NaN

In [ ]:
moradores_max = df['moradores'].max()
moradores_min = df['moradores'].min()

df['moradores_normal'] = (df['moradores'] - moradores_min) / (moradores_max - moradores_min)

In [ ]:
df = df.drop(56)

df['peso_inteiro'] = df['peso'].astype(int)

In [ ]:
df['moradores_inteiro'] = df['moradores_normal'].astype(int)
print(df)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [ ]:
df.to_csv('dados_limpos.csv', index=False)